# Generated by Django 4.2.11 on 2024-03-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='price',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
